site_name: rms1000watt
pages:
  - Home: index.md
  - Dev:
    - Golang: dev/golang.md
    - Reactjs: dev/reactjs.md
    - Python: dev/python.md
    - HTML: dev/html.md
    - Serialization: dev/serialization.md
  - DevOps: 
    - Kubernetes: devops/kubernetes.md
    - Serverless: devops/serverless.md
    - AWS: devops/aws.md
  - Hack: 
    - Security: hack/security.md
    - SBCs: hack/sbcs.md
  - About: about.md